mode: daemonset

presets:
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
  kubeletMetrics:
    enabled: false
  logsCollection:
    enabled: true

config:
  exporters:
    loki:
      # Configuration for sending traces to Loki
      endpoint: http://172.20.26.18:3100/loki/api/v1/push
      timeout: 10s
      read_buffer_size: 200
      write_buffer_size: 100
      retry_on_failure: 
        enabled: true
        initial_interval: 10s
        max_interval: 60s
        max_elapsed_time: 10m
      default_labels_enabled:
        exporter: true
        job: true
        instance: true
        level: true

  processors:
    resource:
      attributes:
        - action: insert
          key: cluster_name
          # generate the cluster name from the cluster_name label
          value: cluster1
          # value: cluster2
        - action: insert
          key: loki.resource.labels
          value: cluster_name,k8s.service.name,k8s.namespace.name,k8s.pod.name,k8s.container.name,k8s.deployment.name,k8s.node.name,k8s.daemonset.name,k8s.cronjob.name,k8s.job.name,k8s.pod.uid

  service:
    pipelines:
      logs:
        exporters:
          - loki
        processors:
          - memory_limiter
          - k8sattributes
          - resource
          - batch

clusterRole:
  create: true
